// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vaibxlwbedjxliwxvhrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhaWJ4bHdiZWRqeGxpd3h2aHJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MDU2MjUsImV4cCI6MjA2NzE4MTYyNX0.Y5M_-nihAvo-oCrlrxB-djhfLitlmbmx4LxOOE7fZBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});